fix: NPE when retrieving the QuarkusRunContext
This fixes the following exception, happening when a project is opened:

```java
java.lang.NullPointerException: Cannot invoke "javax.swing.JComponent.getClientProperty(Object)" because the return value of "com.intellij.execution.ui.RunContentDescriptor.getComponent()" is null
	at com.redhat.devtools.intellij.quarkus.run.QuarkusRunContext.getContext(QuarkusRunContext.java:34)
	at com.redhat.devtools.intellij.quarkus.run.QuarkusDevActionGroup.update(QuarkusDevActionGroup.java:32)
```

Signed-off-by: George Gastaldi <gegastaldi@gmail.com>