java.lang.NullPointerException: Cannot invoke "java.util.concurrent.CompletableFuture.thenRun(java.lang.Runnable)" because "this.initializeFuture" is null
Fixes #748

Signed-off-by: azerr <azerr@redhat.com>